# Generated by Django 3.1.7 on 2021-05-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_maincycle_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maincycle',
            name='user',
        ),
    ]
